### ISSUE TITLE
chroot fails on Mac when UID or GID is negative

### ISSUE THREAD

**Issue by ericlenio** [timkuijsten/node-chroot#5]
Running on macOS Ventura 13.2.1 and trying to chroot with user/group of nobody/nobody and seeing this:

```
../src/node_credentials.cc:220:void node::credentials::SetGid(const FunctionCallbackInfo<v8::Value> &): Assertion `args[0]->IsUint32() || args[0]->IsString()' failed.
```

It seems to be due to the `nobody` group is -2, so the assertion of uint32 fails:

```
grep nobody | /etc/group
nobody:*:-2:
```

Similarly, the UID for `nobody` is also -2. Not sure if the assertions for UID/GID can be relaxed to allow negative numbers?

**Comment by ericlenio** [comment]
I guess this is really an issue with the posix package, closing.

**Comment by timkuijsten** [comment]
I think so too, but good to know macOS has negative group ids, tnx!

**Comment by ericlenio** [comment]
I have a little more detail. The assertion is actually from [node source](https://github.com/nodejs/node/blob/v16.19.1/src/node_credentials.cc#L223). The [posix spec](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/) does not seem to specifically say git_t/uid_t must be unsigned so I think node got it wrong.

**Comment by timkuijsten** [comment]
Thanks for sharing!
